version: '3.8'

services:
  react_app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: react_app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./:/app
